globalvar bulletIsActivated;
globalvar isPaused;
globalvar bulletAmount;
globalvar maxBullets;
global.clock=0;
maxBullets= 10;
bulletAmount= 0;
currentSpeed = 0;
globalvar preSpeed;
preSpeed=0;
isPaused = false;